### ISSUE TITLE
Google Drive not working

### ISSUE THREAD

**Issue by ltjdym** [AnalogJ/quietthyme.plugin#25]
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, https://api.kloudless.com/services/gdrive/callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/712909987875-p2ff1kp3ohm7ubrjc8ntl94nud24nr1u.apps.googleusercontent.com?project=712909987875

Learn more

Request Details
scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/activity https://www.googleapis.com/auth/drive
redirect_uri=https://api.kloudless.com/services/gdrive/callback
response_type=code
client_id=712909987875-p2ff1kp3ohm7ubrjc8ntl94nud24nr1u.apps.googleusercontent.com
access_type=offline
approval_prompt=force
That’s all we know.

**Comment by AnalogJ** [comment]
Hm, I saw your submitted ticket regarding this issue as well. Let me take a look at this issue and update you there.
