### ISSUE TITLE
Not working on Calibre 3.3

### ISSUE THREAD

**Issue by ideologysec** [AnalogJ/quietthyme.plugin#7]
version 1.0.7 gives a blank screen (since the backend website appears to be unreachable)

version 1.0.8 complains about \_init\_.py not existing, no matter what I do (or how I attempt to debug it)

EDIT: I stand corrected. I needed to build the plugin, have it complain, _enable_ it via terminal, and then I was able to customize plugin inside of Calibre's settings. The web page that it's trying to connect to is returning 404, however. :/

**Comment by AnalogJ** [comment]
Hey, @Aktariel 
Yeah, I ended up re-writing the quietthyme backend, so this is still a work-in-progress. 
I'll update you when the plugin (and the quietthyme service) is working again.
